apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-kubernetes-deploy
  labels:
    name: example-kubernetes-deploy
    app: example-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-kubernetes
      type: example-kubernetes
  template:
    metadata:
      name: example-kubernetes-pod
      labels:
        app: example-kubernetes
        type: example-kubernetes
    spec:
      containers:
        - image: chilaquilchk/examplekubernetes:latest
          imagePullPolicy: IfNotPresent
          name: example-kubernetes-app
          ports:
            - containerPort: 80