apiVersion: v1
kind: Service
metadata:
  name: example-kubernetes-service
  labels:
    name: example-kubernetes-service
    app: example-kubernetes
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: example-kubernetes